### PR TITLE
Upgrade for SonarQube 4.x support

### PR DESCRIPTION
**Pull request by zippy1978**
Here is what I did:
 * Upgraded dependencies
 * Removed some deprecated code
 * Rewrote some parts
 * Fixed unit tests
 * Tests with versions 4.3.3 and 4.5.1
 * Moved to version 0.4-SNAPSHOT

Regards,
Gilles

### CODE REVIEW

**Comment by xfreebird** [comment]
That is awesome !   :+1:  
Great pull request ! :)

**Comment by xfreebird** [comment]
Hmm, it seems that is not showing the oclint reported issues.

**Comment by zippy1978** [comment]
It works on my side.
Which version of OCLint do you use ?
Is your OCLint report fine on the client side ?

**Comment by xfreebird** [comment]
oclint 0.8.1
this is my generated oclint report https://www.dropbox.com/s/1oxmecw8ktym462/ocllint.xml?dl=0
and the sonar log https://www.dropbox.com/s/s1g89rm6k6lic9y/sonar.log?dl=0

**Comment by zippy1978** [comment]
Ok I'll have a look at this...
Did you clean your sonar test instance ? (In order to reimport the profile)

**Comment by xfreebird** [comment]
It could be that in the report the priority is 5 while in code the min priority is 4
+    private static final int OCLINT_MINIMUM_PRIORITY = 4;
src/main/java/org/sonar/plugins/objectivec/violations/OCLintRuleParser.java

**Comment by xfreebird** [comment]
Not quite, I just reinstall the plugin. How do you do it without reseting all sonar settings ?

**Comment by xfreebird** [comment]
Yeah, you were right :) my test data had wrong paths.

**Comment by zippy1978** [comment]
So everything is fine now ?

**Comment by xfreebird** [comment]
Yes.

În data de marți, 6 ianuarie 2015, Gilles Grousset <notifications@github.com>
a scris:

**Comment by zippy1978** [comment]
I'm curious : how did you get to re-install the profile without loosing your Sonar config ?

**Comment by xfreebird** [comment]
I didn't. I just owerite the plugin, and restart sonar.

**Comment by zippy1978** [comment]
OK, thank you.

**Pull request merged**
